# Generated by Django 4.2 on 2023-04-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ration_shop_app', '0003_card_product_item_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
