# Generated by Django 4.2 on 2023-04-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0004_product_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='user',
        ),
    ]
