# Generated by Django 4.2 on 2023-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0007_remove_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
