# Generated by Django 3.2.5 on 2023-05-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0010_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='citizen',
            new_name='cust',
        ),
    ]
