# Generated by Django 3.2.5 on 2023-05-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0011_rename_citizen_cart_cust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='amount',
        ),
    ]
