# Generated by Django 3.2.5 on 2023-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0012_rename_price_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='cust',
        ),
        migrations.AddField(
            model_name='member',
            name='cust',
            field=models.ManyToManyField(null=True, to='ration_shop_app.Customer'),
        ),
    ]
