# Generated by Django 3.2.5 on 2023-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0015_card_allowed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
