# Generated by Django 4.1.3 on 2023-05-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('shop_number', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('item', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('booking_date', models.DateField(auto_now=True)),
                ('pickup_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopowner', models.CharField(default='shopowner', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cardnumber', models.IntegerField()),
                ('cardtype', models.CharField(max_length=10)),
                ('cardcolor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='custreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cardnumber', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(default='address', max_length=50)),
                ('place', models.CharField(default='place', max_length=50)),
                ('panchayat', models.CharField(default='panchayat', max_length=50)),
                ('wardno', models.IntegerField(default=0)),
                ('houseno', models.IntegerField(default=0)),
                ('membersno', models.IntegerField(default=0)),
                ('cardtype', models.CharField(default='type', max_length=50)),
                ('cardcolor', models.CharField(default='color', max_length=50)),
                ('phoneno', models.IntegerField(default=0)),
                ('approve', models.CharField(default='declined', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('shopowner', models.CharField(default='shopowner', max_length=25)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=10)),
                ('card_number', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('occu', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('approve', models.CharField(default='decline', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shopreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(default='address', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('licence', models.CharField(default='licence number', max_length=50)),
                ('shop_number', models.CharField(default='shop number', max_length=50, unique=True)),
                ('contact_number', models.IntegerField(default=0)),
                ('place', models.CharField(default='place', max_length=50)),
                ('approve', models.CharField(default='declined', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='carditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardcolor', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemlist')),
            ],
        ),
    ]
