# Generated by Django 4.1.3 on 2023-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'approved'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
