# Generated by Django 4.2.6 on 2023-11-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custreg',
            name='houseno',
        ),
        migrations.RemoveField(
            model_name='custreg',
            name='panchayat',
        ),
        migrations.RemoveField(
            model_name='custreg',
            name='wardno',
        ),
    ]
