# Generated by Django 4.2.6 on 2023-11-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_custreg_houseno_remove_custreg_panchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custreg',
            name='ration_card',
            field=models.FileField(blank=True, null=True, upload_to='ration_cards/'),
        ),
    ]
