# Generated by Django 4.2.6 on 2023-11-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_custreg_ration_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custreg',
            name='phoneno',
        ),
    ]
