# Generated by Django 4.2.6 on 2023-11-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_custreg_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custreg',
            name='cardcolor',
        ),
        migrations.RemoveField(
            model_name='custreg',
            name='cardtype',
        ),
    ]
