# Generated by Django 4.2.6 on 2023-11-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_custreg_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custreg',
            old_name='color',
            new_name='cardcolor',
        ),
    ]
