# Generated by Django 3.2.5 on 2023-05-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0014_auto_20230506_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='allowed_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
