# Generated by Django 5.0 on 2024-02-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0017_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assigned_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.card'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.product_item'),
        ),
    ]
