# Generated by Django 5.0 on 2024-02-19 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0017_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='availability_timings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='delivery_zones',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='registration_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='vehicle_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
