# Generated by Django 5.0 on 2024-02-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0018_usertype_address_usertype_availability_timings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
