# Generated by Django 5.0 on 2024-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0019_usertype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
