# Generated by Django 5.0 on 2024-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0020_product_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='allowed_quantity',
        ),
        migrations.AlterField(
            model_name='product_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
