# Generated by Django 5.0 on 2024-03-12 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0021_remove_card_allowed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='delete_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
