# Generated by Django 5.0 on 2024-03-12 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0022_usertype_delete_date_usertype_delete_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='type',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='delete_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
