# Generated by Django 5.0 on 2024-03-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0024_rename_role_usertype_type_alter_usertype_delete_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.usertype')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.cart')),
            ],
        ),
    ]
