# Generated by Django 5.0 on 2024-03-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0027_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
