# Generated by Django 5.0 on 2024-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0028_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
