# Generated by Django 5.0 on 2024-03-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0029_cart_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='accepted',
        ),
    ]
