# Generated by Django 5.0 on 2024-03-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0031_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
