# Generated by Django 5.0 on 2024-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0033_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
