# Generated by Django 3.2.25 on 2024-03-17 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0034_pay_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
