# Generated by Django 3.2.25 on 2024-03-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0036_chatbotmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
    ]
