# Generated by Django 3.2.25 on 2024-03-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0019_deliveryboy'),
        ('ration_shop_app', '0037_delete_chatbotmessage'),
    ]

    operations = [
    ]
