# Generated by Django 3.2.25 on 2024-03-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0038_merge_0019_deliveryboy_0037_delete_chatbotmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assigned_month',
        ),
        migrations.AlterField(
            model_name='product',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.card'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ration_shop_app.product_item'),
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
