# Generated by Django 3.2.25 on 2024-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0039_auto_20240327_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('items_bought', models.TextField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
