# Generated by Django 3.2.25 on 2024-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0041_alter_deliverydetail_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
