# Generated by Django 3.2.25 on 2024-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0042_alter_deliverydetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
