# Generated by Django 3.2.25 on 2024-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0043_alter_deliverydetail_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='items_bought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
