# Generated by Django 3.2.25 on 2024-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_shop_app', '0044_auto_20240402_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='delivery_success',
            field=models.BooleanField(default=False),
        ),
    ]
